### ISSUE TITLE
Sword sweep-attack doesn't do damage

### ISSUE THREAD

**Issue by iPyronic** [SpigotMC/SpigotCraft#121] opened 2016-02-26 00:29 UTC
The new sword sweep attack is supposed to knock back and damage nearby entities. It does this both in singleplayer and on a vanilla pre-release 3 server.

On the spigot test server, nearby entities are knocked back, but no AoE damage is dealt. According the the [wiki](http://minecraft.gamepedia.com/15w49a#Other), the nearby entities are supposed to receive 1 damage (a half-heart).

**Comment by md-5** [comment] 2016-02-26 02:41
How do you sweep attack?

**Comment by iPyronic** [comment] 2016-02-26 02:49
You can do a sweep attack with a sword by "moving at walking speed or slower" when you attack, which will then cause nearby mobs to get knocked back as well. Your "attack speed meter must be filled for it to work".

It did no damage and only knocked back when it was first implemented, but a later snapshot made it do damage too.

**Comment by md-5** [comment] 2016-02-26 04:03
Gonna close this as cannot reproduce. Please open a new ticket on release if it still happens

**Closed as completed by md-5** 2016-02-26 04:03 UTC
