### ISSUE TITLE
Logging into the server problem?

### ISSUE THREAD

**Issue by wyatt-herkamp** [SpigotMC/SpigotCraft#339] opened 2018-01-05 23:29 UTC
This happens on loading terrain
https://imgur.com/a/ftQto

**Comment by md-5** [comment] 2018-01-05 23:34
Please get your client log

**Comment by wyatt-herkamp** [comment] 2018-01-05 23:36
`18:31:13] [Client thread/INFO]: Connecting to craft.spigotmc.net., 25565
[18:31:14] [Client thread/WARN]: Unknown custom packed identifier: REGISTER
[18:31:15] [Client thread/INFO]: [CHAT] KingTux joined the game
[18:31:30] [Client thread/ERROR]: Realms module missing
[18:31:31] [Client thread/INFO]: Loaded 0 recipes
[18:31:31] [Client thread/INFO]: Loaded 0 advancements
[18:31:31] [Server thread/INFO]: Starting integrated minecraft server version 18w01a
[18:31:31] [Server thread/INFO]: Generating keypair
[18:31:31] [Server thread/INFO]: Found new data pack vanilla, loading it automatically`

**Comment by md-5** [comment] 2018-01-05 23:36
Are you KingTux?

**Comment by md-5** [comment] 2018-01-05 23:38
What were you doing before you got disconnected for the first time?

**Comment by wyatt-herkamp** [comment] 2018-01-05 23:38
Yes loading the game

**Comment by md-5** [comment] 2018-01-05 23:39
Yeah but last time you were playing on the server, what did you do.
I think there is a bugged item in your inventory, but I need to know how you got it.

**Comment by wyatt-herkamp** [comment] 2018-01-05 23:40
I was messing with https://github.com/SpigotMC/SpigotCraft/issues/338

**Comment by md-5** [comment] 2018-01-05 23:40
Do you have any idea what you put in the rename box?

**Comment by wyatt-herkamp** [comment] 2018-01-05 23:40
I had those bugged items in my Inventory. That must be it.

**Comment by wyatt-herkamp** [comment] 2018-01-05 23:41
"Moo" Then it would turn into that weird text and then to a whole bunch of /'s

**Comment by wyatt-herkamp** [comment] 2018-01-05 23:42
I am guessing that my inventory will have to be cleared. Let me try to join on my alt.

**Comment by md-5** [comment] 2018-01-05 23:46
I've reset your inventory.

For some reason the item landed up like this:
```{"text":"{\"text\":\"{\\\"text\\\":\\\"{\\\\\\\"text\\\\\\\":\\\\\\\"{\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"{\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"{\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"{\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"{\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"text\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"{\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"}```

I'm hoping that it was just a result of #338 and won't be caused by 1.12 saved data (or weird names in 1.13)

**Comment by wyatt-herkamp** [comment] 2018-01-05 23:47
That is what it was turning into. I could only see a few of them due to screen width. Thx @md-5 :+1:

**Comment by md-5** [comment] 2018-01-05 23:47
Gonna leave open for a bit

**Closed as completed** 2018-01-12 05:51 UTC
Labels: bukkit, solved
